### PR TITLE
Creation of LICENSE to add a license

### PR DESCRIPTION
**Pull request by s-a-m**
By default, any creative work without an explicit license, including Github repositories, have the most restrictive of them all: exclusive "all rights reserved" copyright. I assume that since you have your (awesome) software in a Github repository, it is your intent for people to use it, fork it and improve it. Thus, I'd strongly advise to add an open source license to facilitate this -- otherwise, it would be illegal to use this code in any way. If you want to allow any use of it, I'd recommend a MIT License. Since you may opt to protect its code from any third-party wanting to profit from it, you may prefer to use the AGPL License (which is the one I'm including in this pull-request). I am happy to help clarify doubts or uncertainties around all this, or help choose another license if you don't like these.

### CODE REVIEW

**Comment by Akronix** [comment]
Hi @s-a-m !

Since this repo it's actually a compilation of many scripts, most of the directories in this repo has its own particular license, depending on the source code and the author.  The only ones that don't are: get_bot_users and wikia_census. For the former one, I will add a LICENSE like GPL. For the second one, there's some code written from someone outside the GRASIA group, so we should get his consent in order to set an arbitrary open-source license.

**Comment by Akronix** [comment]
Anyhow, please, let me know if this way of setting different licenses for different directories is correct or not.

**Comment by s-a-m** [comment]
Sounds good! I would add anyhow a LICENSE file in the root directory explaining this situation, and ideally specifying the licence of each of the scripts.

**Comment by Akronix** [comment]
Done! Thank you @s-a-m !

**Pull request closed without merging**
